package com.kony.appfactory.enums

public enum ChannelType implements Serializable {
    ANDROID_MOBILE_NATIVE, ANDROID_TABLET_NATIVE, IOS_MOBILE_NATIVE, IOS_TABLET_NATIVE, ANDROID_UNIVERSAL_NATIVE, IOS_UNIVERSAL_NATIVE
}